export type Hotel = {
  slug: string;
  name: string;
  city: string;
  /** Destination slug this hotel belongs to (links it to a destination page). */
  destination?: string;
  /** Extra destination slugs this hotel should also appear under (e.g. an Aswan
   *  hotel used as a day-trip base for Abu Simbel). */
  alsoIn?: string[];
  area: string;
  stars: number;
  rating: string;
  reviewCount: number;
  pricePerNight: number;
  image: string;
  gallery: string[];
  description: string[];
  amenities: string[];
  category: "Luxury" | "Boutique" | "Resort" | "Value" | "Comfort" | "Eco-lodge";
};

/** Real hotel photos live under public/img/hotels/<slug>-1.jpg .. -N.jpg. */
const G = (slug: string, n: number) =>
  Array.from({ length: n }, (_, i) => `/img/hotels/${slug}-${i + 1}.jpg`);

export const hotels: Hotel[] = [
  /* ============================= CAIRO & GIZA ============================= */
  {
    slug: "marriott-mena-house",
    name: "Marriott Mena House",
    city: "Giza",
    destination: "cairo",
    area: "Pyramids Road, at the foot of the Giza plateau",
    stars: 5,
    rating: "4.7",
    reviewCount: 9200,
    pricePerNight: 240,
    image: G("marriott-mena-house", 4)[0],
    gallery: G("marriott-mena-house", 4),
    description: [
      "A historic palace hotel set in 40 acres of gardens right at the foot of the pyramids, dating back to 1869 and once a royal hunting lodge.",
      "The pyramid-view rooms put the Great Pyramid in your window — the most dramatic stay in Giza, with the monuments a short walk away.",
    ],
    amenities: ["Pyramid-view rooms", "Outdoor pool", "Gardens", "Several restaurants", "Spa", "Airport transfer"],
    category: "Luxury",
  },
  {
    slug: "cairo-marriott",
    name: "Cairo Marriott Hotel",
    city: "Cairo",
    destination: "cairo",
    area: "Zamalek, Nile island",
    stars: 5,
    rating: "4.5",
    reviewCount: 11800,
    pricePerNight: 160,
    image: G("cairo-marriott", 2)[0],
    gallery: G("cairo-marriott", 2),
    description: [
      "Built around the 19th-century Gezirah Palace on the leafy island of Zamalek, this grand hotel pairs restored Khedival halls with two modern garden towers.",
      "It is a central, characterful base — walkable cafés and the Nile on the doorstep, and the Egyptian Museum a short drive away.",
    ],
    amenities: ["Palace gardens", "Outdoor pool", "Multiple restaurants", "Free Wi-Fi", "Fitness centre", "Airport transfer"],
    category: "Luxury",
  },
  {
    slug: "nile-ritz-carlton",
    name: "The Nile Ritz-Carlton, Cairo",
    city: "Cairo",
    destination: "cairo",
    area: "Tahrir Square, Nile-front",
    stars: 5,
    rating: "4.6",
    reviewCount: 6400,
    pricePerNight: 220,
    image: G("nile-ritz-carlton", 4)[0],
    gallery: G("nile-ritz-carlton", 4),
    description: [
      "A polished riverside landmark on Tahrir Square, right beside the Egyptian Museum and overlooking the Nile.",
      "It is the most central luxury base in Cairo, with river-view rooms and the old city, museums and downtown all within reach.",
    ],
    amenities: ["Nile-view rooms", "Outdoor pool", "Spa", "Multiple restaurants", "Fitness centre", "Airport transfer"],
    category: "Luxury",
  },
  {
    slug: "pyramids-view-inn",
    name: "Pyramids View Inn",
    city: "Giza",
    destination: "cairo",
    area: "Nazlet El-Samman, facing the plateau",
    stars: 3,
    rating: "4.5",
    reviewCount: 1180,
    pricePerNight: 45,
    image: G("pyramids-view-inn", 1)[0],
    gallery: G("pyramids-view-inn", 1),
    description: [
      "A small, long-running guesthouse a short walk from the Giza gate, with simple rooms and a rooftop that looks straight at the Sphinx and the pyramids.",
      "You trade fancy facilities for one of the best views in Giza and a breakfast served with the pyramids in front of you.",
    ],
    amenities: ["Pyramid-view rooms", "Rooftop breakfast", "Free Wi-Fi", "Air conditioning", "Free airport pickup"],
    category: "Value",
  },

  /* ================================ LUXOR ================================ */
  {
    slug: "sofitel-winter-palace",
    name: "Sofitel Winter Palace Luxor",
    city: "Luxor",
    destination: "luxor",
    area: "East Bank corniche, beside Luxor Temple",
    stars: 5,
    rating: "4.6",
    reviewCount: 5100,
    pricePerNight: 190,
    image: G("sofitel-winter-palace", 4)[0],
    gallery: G("sofitel-winter-palace", 4),
    description: [
      "A grand Victorian hotel from 1907 on the Nile-front corniche, set in famous gardens a short walk from Luxor Temple.",
      "Howard Carter announced the discovery of Tutankhamun's tomb from its steps — it is the most storied address on the East Bank.",
    ],
    amenities: ["Nile-view rooms", "Royal gardens", "Outdoor pool", "Restaurants & bar", "Spa", "Walk to Luxor Temple"],
    category: "Luxury",
  },
  {
    slug: "steigenberger-nile-palace-luxor",
    name: "Steigenberger Nile Palace Luxor",
    city: "Luxor",
    destination: "luxor",
    area: "East Bank, Nile-front",
    stars: 5,
    rating: "4.4",
    reviewCount: 4300,
    pricePerNight: 105,
    image: G("steigenberger-nile-palace-luxor", 2)[0],
    gallery: G("steigenberger-nile-palace-luxor", 2),
    description: [
      "A large, comfortable Nile-front resort on the East Bank, with river-view rooms, big pools and several restaurants.",
      "A reliable mid-range base within easy reach of Karnak and Luxor Temple, good for families who want space and facilities.",
    ],
    amenities: ["Nile-view rooms", "Two pools", "Multiple restaurants", "Spa & gym", "Free Wi-Fi", "Airport transfer"],
    category: "Comfort",
  },
  {
    slug: "sonesta-st-george-luxor",
    name: "Sonesta St. George Hotel Luxor",
    city: "Luxor",
    destination: "luxor",
    area: "East Bank corniche",
    stars: 5,
    rating: "4.5",
    reviewCount: 3600,
    pricePerNight: 95,
    image: G("sonesta-st-george-luxor", 4)[0],
    gallery: G("sonesta-st-george-luxor", 4),
    description: [
      "A riverfront five-star on the corniche with Nile-view rooms, a waterside pool and a short walk to Luxor Temple and the museum.",
      "Fair value for its position and comfort, and an easy base for both banks of the river.",
    ],
    amenities: ["Nile-view rooms", "Riverside pool", "Restaurants & bar", "Spa", "Free Wi-Fi", "Central corniche location"],
    category: "Comfort",
  },
  {
    slug: "eatabe-luxor",
    name: "Aracan Eatabe Luxor Hotel",
    city: "Luxor",
    destination: "luxor",
    area: "East Bank, Corniche el Nil",
    stars: 4,
    rating: "4.2",
    reviewCount: 1340,
    pricePerNight: 80,
    image: G("eatabe-luxor", 1)[0],
    gallery: G("eatabe-luxor", 1),
    description: [
      "A long-running corniche hotel set in its own gardens, with an outdoor pool and rooms looking over greenery or the Nile.",
      "Its central location puts Luxor Temple, the museum and the West Bank ferry within easy walking distance — a practical, fair-priced base.",
    ],
    amenities: ["Outdoor pool", "Nile-view rooms", "Poolside bar", "Restaurant", "Free Wi-Fi", "Air conditioning"],
    category: "Comfort",
  },

  /* ================================ ASWAN ================================ */
  {
    slug: "sofitel-old-cataract",
    name: "Sofitel Legend Old Cataract Aswan",
    city: "Aswan",
    destination: "aswan",
    alsoIn: ["abu-simbel"],
    area: "Above the First Cataract of the Nile",
    stars: 5,
    rating: "4.7",
    reviewCount: 4800,
    pricePerNight: 380,
    image: G("sofitel-old-cataract", 4)[0],
    gallery: G("sofitel-old-cataract", 4),
    description: [
      "A Victorian palace hotel from 1899 perched on a pink-granite bluff above the Nile, with views over Elephantine Island and the desert.",
      "Agatha Christie wrote part of Death on the Nile here — it is the most memorable splurge on the river, and a grand base either side of an Abu Simbel trip.",
    ],
    amenities: ["Nile-view rooms", "Gardens & terrace", "Pool", "Spa", "Fine dining", "Airport transfer"],
    category: "Luxury",
  },
  {
    slug: "movenpick-aswan",
    name: "Mövenpick Resort Aswan",
    city: "Aswan",
    destination: "aswan",
    alsoIn: ["abu-simbel"],
    area: "Elephantine Island, Nile",
    stars: 5,
    rating: "4.5",
    reviewCount: 6300,
    pricePerNight: 170,
    image: G("movenpick-aswan", 4)[0],
    gallery: G("movenpick-aswan", 4),
    description: [
      "A large resort on its own island in the Nile, reached by a short boat shuttle, with a rooftop bar that looks out over Aswan.",
      "Comfortable and reliable, with island gardens and a pool — and an easy base if you'd rather visit Abu Simbel on an early day-trip and come back to the city.",
    ],
    amenities: ["Nile-view rooms", "Infinity pool", "Rooftop restaurant & bar", "Gardens", "Boat shuttle", "Free Wi-Fi"],
    category: "Resort",
  },
  {
    slug: "basma-hotel-aswan",
    name: "Basma Hotel Aswan",
    city: "Aswan",
    destination: "aswan",
    area: "On the hill beside the Nubian Museum",
    stars: 4,
    rating: "4.3",
    reviewCount: 980,
    pricePerNight: 100,
    image: G("basma-hotel-aswan", 3)[0],
    gallery: G("basma-hotel-aswan", 3),
    description: [
      "Basma sits on high ground above town, so many rooms look out over the Nile and the surrounding greenery.",
      "A dependable mid-range base with a garden, a pool and an easy walk to the Nubian Museum, without resort prices.",
    ],
    amenities: ["Outdoor pool", "Terraced garden", "Restaurant & poolside bar", "Spa", "Free Wi-Fi", "Free parking"],
    category: "Comfort",
  },
  {
    slug: "pyramisa-isis-island",
    name: "Pyramisa Isis Island Aswan Resort & Spa",
    city: "Aswan",
    destination: "aswan",
    area: "Isis Island (private island, boat shuttle)",
    stars: 5,
    rating: "4.4",
    reviewCount: 2450,
    pricePerNight: 125,
    image: G("pyramisa-isis-island", 3)[0],
    gallery: G("pyramisa-isis-island", 3),
    description: [
      "The resort takes up its own green island in the Nile, reached by a short boat shuttle, so every room looks onto water, gardens or the hills.",
      "A roomy, quiet retreat with several pools and restaurants, good for families and couples who want space away from the town.",
    ],
    amenities: ["Private island & shuttle", "Three pools", "Four restaurants", "Spa & sauna", "Tennis & squash", "Kids' playground"],
    category: "Resort",
  },

  /* ============================== ABU SIMBEL ============================== */
  {
    slug: "eskaleh-ecolodge",
    name: "Eskaleh Nubian Ecolodge",
    city: "Abu Simbel",
    destination: "abu-simbel",
    area: "On the lake edge, near the temples",
    stars: 3,
    rating: "4.7",
    reviewCount: 430,
    pricePerNight: 75,
    image: G("eskaleh-ecolodge", 1)[0],
    gallery: G("eskaleh-ecolodge", 1),
    description: [
      "A small mud-brick lodge run by a local Nubian owner, with only a handful of rooms and a home-cooked menu.",
      "The most characterful place to stay in the village, on the lake edge a short distance from the temples — the reason to stay over rather than day-trip.",
    ],
    amenities: ["Lake-view rooms", "Traditional restaurant", "Garden & sun terrace", "Sunrise boat trips", "Free Wi-Fi", "Free parking"],
    category: "Eco-lodge",
  },
  // Abu Simbel's other "where to stay" options are the Aswan day-trip bases
  // (Sofitel Old Cataract, Mövenpick Aswan) surfaced via their alsoIn field above.

  /* ============================== ALEXANDRIA ============================== */
  {
    slug: "steigenberger-cecil",
    name: "Steigenberger Cecil Hotel",
    city: "Alexandria",
    destination: "alexandria",
    area: "Saad Zaghloul Square, seafront",
    stars: 4,
    rating: "4.3",
    reviewCount: 4100,
    pricePerNight: 90,
    image: G("steigenberger-cecil", 4)[0],
    gallery: G("steigenberger-cecil", 4),
    description: [
      "A 1929 landmark on Saad Zaghloul Square overlooking the Eastern Harbour, full of old-Alexandria character — Churchill and Somerset Maugham once stayed here.",
      "It is the most atmospheric central base in the city, walkable to the corniche, the souk and the tram.",
    ],
    amenities: ["Sea-view rooms", "Rooftop restaurant", "Bar", "Free Wi-Fi", "Air conditioning", "Central seafront"],
    category: "Boutique",
  },
  {
    slug: "four-seasons-san-stefano",
    name: "Four Seasons Hotel Alexandria at San Stefano",
    city: "Alexandria",
    destination: "alexandria",
    area: "San Stefano, seafront",
    stars: 5,
    rating: "4.6",
    reviewCount: 3900,
    pricePerNight: 210,
    image: G("four-seasons-san-stefano", 3)[0],
    gallery: G("four-seasons-san-stefano", 3),
    description: [
      "A modern beachfront five-star at San Stefano, with sea-view rooms, a private beach and a large pool over the Mediterranean.",
      "The polished option in Alexandria, a short drive from the historic centre, for travellers who want full facilities and the sea on the doorstep.",
    ],
    amenities: ["Private beach", "Sea-view rooms", "Outdoor & indoor pools", "Spa", "Several restaurants", "Airport transfer"],
    category: "Luxury",
  },
  {
    slug: "windsor-palace-alexandria",
    name: "Windsor Palace Luxury Heritage Hotel",
    city: "Alexandria",
    destination: "alexandria",
    area: "Corniche / Raml Station",
    stars: 4,
    rating: "4.3",
    reviewCount: 1290,
    pricePerNight: 75,
    image: G("windsor-palace-alexandria", 4)[0],
    gallery: G("windsor-palace-alexandria", 4),
    description: [
      "A 1906 seafront hotel with high painted ceilings, antiques and balconies looking straight over the Corniche and the Mediterranean.",
      "You stay for the building and the view, not the gadgets — a piece of old Alexandria in the centre of town.",
    ],
    amenities: ["Sea-view balcony rooms", "Rooftop breakfast terrace", "Restaurant & bar", "Free Wi-Fi", "Air conditioning", "Room service"],
    category: "Boutique",
  },
  {
    slug: "tolip-alexandria",
    name: "Tolip Hotel Alexandria",
    city: "Alexandria",
    destination: "alexandria",
    area: "Roushdy, Corniche Road",
    stars: 5,
    rating: "4.3",
    reviewCount: 2040,
    pricePerNight: 85,
    image: G("tolip-alexandria", 1)[0],
    gallery: G("tolip-alexandria", 1),
    description: [
      "A large modern hotel on the Corniche with a private beach, a sea-view pool and a spa, good for travellers who want full facilities and space.",
      "Every room has a balcony, and the upper floors look right out over the water.",
    ],
    amenities: ["Private beach", "Outdoor pool", "Spa & fitness", "Several restaurants", "Balcony in every room", "Airport transfer"],
    category: "Comfort",
  },

  /* =========================== SHARM EL SHEIKH =========================== */
  {
    slug: "reef-oasis-beach",
    name: "Reef Oasis Beach Resort",
    city: "Sharm El Sheikh",
    destination: "sharm-el-sheikh",
    area: "Hadaba, on Temple Reef",
    stars: 5,
    rating: "4.5",
    reviewCount: 6740,
    pricePerNight: 130,
    image: G("reef-oasis-beach", 2)[0],
    gallery: G("reef-oasis-beach", 2),
    description: [
      "Built around its own house reef, this is the one to choose if snorkelling and diving straight off the beach is the point of the trip.",
      "There is a full dive centre on site and plenty of pools, dining and shade for the hours you are out of the water.",
    ],
    amenities: ["Own house reef", "On-site dive centre", "Multiple pools", "Six restaurants & bars", "Spa", "All-inclusive board"],
    category: "Resort",
  },
  {
    slug: "coral-sea-holiday",
    name: "Coral Sea Holiday Resort & Aqua Park",
    city: "Sharm El Sheikh",
    destination: "sharm-el-sheikh",
    area: "Nabq Bay, facing the Straits of Tiran",
    stars: 5,
    rating: "4.3",
    reviewCount: 7180,
    pricePerNight: 110,
    image: G("coral-sea-holiday", 2)[0],
    gallery: G("coral-sea-holiday", 2),
    description: [
      "A big, comfortable all-inclusive in quieter Nabq Bay, with a large aqua park and a long private beach looking out toward Tiran.",
      "It suits travellers who want a full resort day, plenty of pools and food without leaving the grounds.",
    ],
    amenities: ["Aqua park & lazy river", "Four pools + swim-up rooms", "Long private beach", "Six restaurants & seven bars", "Spa", "Kids' facilities"],
    category: "Resort",
  },
  {
    slug: "sharm-holiday-resort",
    name: "Sharm Holiday Resort",
    city: "Sharm El Sheikh",
    destination: "sharm-el-sheikh",
    area: "Hadaba / Um El Sid, short walk to Naama Bay",
    stars: 4,
    rating: "4.1",
    reviewCount: 4120,
    pricePerNight: 60,
    image: G("sharm-holiday-resort", 1)[0],
    gallery: G("sharm-holiday-resort", 1),
    description: [
      "A straightforward all-inclusive that keeps the cost down without cutting the basics, with its own beach and pools minutes from the Naama Bay promenade.",
      "Good for travellers who want sun, sea and full board at a fair price.",
    ],
    amenities: ["Private beach", "Outdoor pool", "All-inclusive board", "Health club & sauna", "Dive & snorkel desk", "Tennis & squash"],
    category: "Value",
  },
  {
    slug: "naama-bay-resort",
    name: "Naama Bay Hotel & Resort",
    city: "Sharm El Sheikh",
    destination: "sharm-el-sheikh",
    area: "Naama Bay, on the promenade",
    stars: 5,
    rating: "4.2",
    reviewCount: 5260,
    pricePerNight: 85,
    image: G("naama-bay-resort", 1)[0],
    gallery: G("naama-bay-resort", 1),
    description: [
      "A central beachfront resort right on the Naama Bay strip, so the cafés, dive shops and nightlife are all on your doorstep.",
      "The aqua park and several pools make it an easy pick for families who want to stay in the middle of things.",
    ],
    amenities: ["Aqua park", "Four pools", "Private Naama Bay beach", "Spa & fitness", "Dive centre", "Daily entertainment"],
    category: "Resort",
  },

  /* ============================== NORTH COAST ============================== */
  {
    slug: "beau-site-matruh",
    name: "Beau Site Hotel Marsa Matruh",
    city: "Marsa Matruh",
    destination: "north-coast",
    area: "Marsa Matruh, near the Corniche",
    stars: 3,
    rating: "4.2",
    reviewCount: 1410,
    pricePerNight: 120,
    image: G("beau-site-matruh", 1)[0],
    gallery: G("beau-site-matruh", 1),
    description: [
      "A long-running beachfront favourite in Marsa Matruh with its own sandy beach and an easy walk into town.",
      "Good value for a relaxed family stay on the water without resort prices, open mainly for the summer season.",
    ],
    amenities: ["Private beach", "Outdoor pool", "Spa & sauna", "Two restaurants", "Free breakfast", "Balcony rooms"],
    category: "Comfort",
  },
  {
    slug: "al-alamein-hotel",
    name: "Al Alamein Hotel",
    city: "Sidi Abdel Rahman",
    destination: "north-coast",
    area: "Sidi Abdel Rahman (Marassi bay)",
    stars: 4,
    rating: "4.3",
    reviewCount: 1760,
    pricePerNight: 130,
    image: G("al-alamein-hotel", 1)[0],
    gallery: G("al-alamein-hotel", 1),
    description: [
      "A historic bayfront resort open since 1960, sitting right on the calm turquoise water of Sidi Abdel Rahman.",
      "Rooms range from garden views to direct beach access, with pools, a spa and several restaurants on site.",
    ],
    amenities: ["Private beach", "Outdoor & kids pools", "Spa", "Fitness & yoga", "Four restaurants", "Sea-view rooms"],
    category: "Resort",
  },
  {
    slug: "porto-matrouh",
    name: "Porto Matrouh Beach Resort",
    city: "Marsa Matruh",
    destination: "north-coast",
    area: "Marsa Matruh",
    stars: 4,
    rating: "4.0",
    reviewCount: 2230,
    pricePerNight: 95,
    image: G("porto-matrouh", 1)[0],
    gallery: G("porto-matrouh", 1),
    description: [
      "An affordable, family-friendly resort in Marsa Matruh with sea-view balconies on every room and a relaxed pool setup.",
      "A solid summer base for exploring the Agiba and Cleopatra beaches nearby.",
    ],
    amenities: ["Outdoor & children's pools", "Private beach (shuttle)", "Restaurant & bar", "Garden", "Playground", "Free parking"],
    category: "Resort",
  },
  {
    slug: "porto-marina-alamein",
    name: "Porto Marina Resort & Spa Al Alamein",
    city: "El Alamein",
    destination: "north-coast",
    area: "Marina, El Alamein",
    stars: 5,
    rating: "4.1",
    reviewCount: 2980,
    pricePerNight: 150,
    image: G("porto-marina-alamein", 1)[0],
    gallery: G("porto-marina-alamein", 1),
    description: [
      "A large resort and water-park complex right at Marina El Alamein, with multiple pools, restaurants and a spa.",
      "The most full-featured option on the coast for travellers who want everything on site, busiest and priciest in peak summer.",
    ],
    amenities: ["Water park", "Multiple pools", "Private beach", "Spa", "Multiple restaurants & bars", "Balcony rooms"],
    category: "Resort",
  },

  /* ================================= SIWA ================================= */
  {
    slug: "adrere-amellal",
    name: "Adrère Amellal",
    city: "Siwa",
    destination: "siwa",
    area: "Lakeside, foot of Adrère Amellal mountain",
    stars: 5,
    rating: "4.6",
    reviewCount: 210,
    pricePerNight: 600,
    image: G("adrere-amellal", 2)[0],
    gallery: G("adrere-amellal", 2),
    description: [
      "The famous one — a kershef lodge built entirely from local salt-rock and mud, lit by beeswax candles instead of electricity.",
      "A quiet, off-grid splurge with an organic garden, a spring-fed pool and rooms that each look different.",
    ],
    amenities: ["Spring-fed pool", "Farm-to-table dining", "Desert excursions", "Lakeside setting", "Candlelit rooms", "Full-board option"],
    category: "Eco-lodge",
  },
  {
    slug: "kenooz-shali-lodge",
    name: "Kenooz Shali Lodge",
    city: "Siwa",
    destination: "siwa",
    area: "Central Siwa, in the palm groves below Shali",
    stars: 3,
    rating: "4.4",
    reviewCount: 410,
    pricePerNight: 70,
    image: G("kenooz-shali-lodge", 2)[0],
    gallery: G("kenooz-shali-lodge", 2),
    description: [
      "A mudbrick village lodge built in the traditional kershef style, with simple rooms, palm-shaded terraces and a small pool under the trees.",
      "The affordable way to get the heritage Siwan feel without the eco-lodge price tag, walkable to everything in town.",
    ],
    amenities: ["Palm-grove pool", "Siwan restaurant", "Terraces over the groves", "Traditional furnishings", "Central location", "Free Wi-Fi"],
    category: "Eco-lodge",
  },
  {
    slug: "taziry-ecovillages",
    name: "Taziry Ecovillages",
    city: "Siwa",
    destination: "siwa",
    area: "Edge of the oasis, near the salt lakes",
    stars: 3,
    rating: "4.5",
    reviewCount: 340,
    pricePerNight: 200,
    image: G("taziry-ecovillages", 1)[0],
    gallery: G("taziry-ecovillages", 1),
    description: [
      "A larger eco-village of palm and mudbrick chalets, some carved into the hillside, set around a natural spring-fed pool.",
      "It keeps the rustic look but adds real comforts like hot water and power, which makes it an easier sell than the fully off-grid lodges.",
    ],
    amenities: ["Spring-fed pool", "Spa", "Restaurant", "Private verandas", "Horse & camel rides", "4x4 desert safaris"],
    category: "Eco-lodge",
  },
];

export const getHotel = (slug: string) => hotels.find((h) => h.slug === slug);
