export type Hotel = {
  slug: string;
  name: string;
  city: string;
  /** Group shown on the Recommended Hotels page, e.g. "Giza", "Cairo", "Hurghada". */
  region: string;
  /** Destination slug this hotel belongs to (links it to a destination page). */
  destination?: string;
  /** Extra destination slugs this hotel should also appear under. */
  alsoIn?: string[];
  area: string;
  stars: number;
  rating: string;
  reviewCount: number;
  pricePerNight: number;
  image: string;
  gallery: string[];
  description: string[];
  amenities: string[];
  category: "Luxury" | "Boutique" | "Resort" | "Value" | "Comfort" | "Eco-lodge";
};

/** Real hotel photos live under public/img/hotels/<slug>-1.jpg .. -N.jpg. */
const G = (slug: string, n: number) =>
  Array.from({ length: n }, (_, i) => `/img/hotels/${slug}-${i + 1}.jpg`);

type Seed = Omit<Hotel, "image" | "gallery"> & { photos: number };
const build = (s: Seed): Hotel => {
  const g = G(s.slug, s.photos);
  const { photos, ...rest } = s;
  void photos;
  return { ...rest, image: g[0], gallery: g.slice(1) };
};

export const hotels: Hotel[] = [
  // ============================ GIZA ============================
  build({
    slug: "steigenberger-pyramids-cairo",
    name: "Steigenberger Pyramids Cairo",
    city: "Giza",
    region: "Giza",
    destination: "cairo",
    area: "By the Grand Egyptian Museum",
    stars: 5,
    rating: "4.5",
    reviewCount: 1247,
    pricePerNight: 0,
    photos: 6,
    category: "Luxury",
    description: [
      "The Steigenberger Pyramids Cairo has the kind of address most Giza hotels can only dream of. It sits right on the Alexandria Road, directly opposite the new Grand Egyptian Museum, with the Pyramids of Giza rising just three kilometres away. From the right room — or from a lounger by the pool — you can catch Khufu's pyramid and the great glass facade of the museum in a single glance, a view no other five-star in the city can quite match.",
      "The heart of the hotel is its garden and the big free-form outdoor pool, ringed by sun loungers and shaded cabanas, with the pyramids sitting on the horizon behind it. It's a genuinely restful place to come back to after a hot morning on the plateau: order a smoothie or a late lunch from the pool bar, take a swim, and let the afternoon go quiet.",
      "Rooms are generous — the standard Deluxe runs to a roomy 36 square metres — and come in a whole spread of views: city, pool, museum, pyramid-side, or full pyramid. The suites climb much higher, up to the vast King Tut and Nefertiti suites, most with a private balcony you'll want to take your morning coffee onto.",
      "It's a big, established five-star rather than a design hotel, and the odd corner shows its age here and there — we'd rather tell you that up front. But for location, views, and all-round comfort right beside the Pyramids and the Grand Egyptian Museum, very little competes.",
    ],
    amenities: ["Outdoor pool with Pyramid views", "Landscaped gardens", "Pyramid, museum & pool-view rooms", "Private balconies", "Lotus restaurant & terrace", "Zoser Bar & pool bar", "Breakfast buffet", "24-hour room service", "Free Wi-Fi throughout", "Airport & sightseeing shuttle"],
  }),
  build({
    slug: "pyramids-park-resort",
    name: "Pyramids Park Resort Cairo",
    city: "Giza",
    region: "Giza",
    destination: "cairo",
    area: "Cairo–Alexandria Desert Road",
    stars: 4,
    rating: "4.2",
    reviewCount: 693,
    pricePerNight: 0,
    photos: 5,
    category: "Resort",
    description: [
      "Pyramids Park Resort spreads across about 25 acres of mature gardens on the Cairo–Alexandria Desert Road, a five-minute drive from the Great Pyramids and roughly half an hour from central Cairo. It's the kind of place where you can walk off the desert heat under real trees, which in this part of Giza is rarer than it sounds.",
      "There are 476 rooms and suites, all with balconies, wrapped around one of the largest outdoor pools in the area — some 1,750 square metres of water. Four restaurants, a piano bar with live music, a spa, a gym and padel courts mean you rarely need to leave, and the sheer scale makes it a comfortable, good-value base for families.",
      "It's an older property (it once flew the InterContinental flag) and it wears that history honestly — some rooms feel dated and upkeep can be uneven — so come for the gardens, the pool, and the space rather than boutique polish. We use it for travellers who want room to breathe near the Pyramids without a five-star price.",
    ],
    amenities: ["Huge outdoor pool (~1,750 m²)", "25 acres of gardens", "Balconies in every room", "Four restaurants", "Piano bar & live music", "Spa & gym", "Padel courts", "Family-friendly", "5 min to the Pyramids", "Free parking"],
  }),
  build({
    slug: "regency-pyramids-view",
    name: "Regency Pyramids View Hotel",
    city: "Giza",
    region: "Giza",
    destination: "cairo",
    area: "Nazlet El-Semman, by the plateau",
    stars: 4,
    rating: "3.9",
    reviewCount: 62,
    pricePerNight: 0,
    photos: 5,
    category: "Boutique",
    description: [
      "The Regency Pyramids View is a small, personal hotel in Nazlet El-Semman, the old village right at the foot of the Giza plateau — close enough that the pyramids fill the sky. It's about a ten-minute walk to the entrance, and the whole point of the place is the view.",
      "That view is best from the rooftop terrace, where the pool and dining area look straight out over the pyramids and the plain of Giza — sunrise and sunset here are the reason to book. Rooms are individually decorated with balconies, many facing the monuments directly, and breakfast and an airport shuttle are included.",
      "Let's be honest: it's a modest, older property, and reviews are mixed on the rooms and upkeep. You don't come for luxury; you come to open your curtains onto the Great Pyramid. For travellers who value that one unbeatable outlook over polish, it's hard to beat.",
    ],
    amenities: ["Rooftop pool & terrace", "Direct Pyramid views", "Balconies facing the monuments", "10-min walk to the Pyramids", "Breakfast included", "Airport shuttle", "Restaurant & rooftop dining", "Small spa"],
  }),
  // ============================ CAIRO ============================
  build({
    slug: "steigenberger-el-tahrir-cairo",
    name: "Steigenberger Hotel El Tahrir Cairo",
    city: "Cairo",
    region: "Cairo",
    destination: "cairo",
    area: "Tahrir Square, Downtown",
    stars: 5,
    rating: "4.6",
    reviewCount: 6245,
    pricePerNight: 0,
    photos: 6,
    category: "Luxury",
    description: [
      "The Steigenberger El Tahrir stands right on Tahrir Square in Downtown Cairo, looking straight across at the old Egyptian Museum — you could not be more central. Khan el-Khalili is a couple of kilometres away, and the whole tangle of downtown Cairo is on your doorstep.",
      "It's a polished, business-friendly five-star with 295 rooms and suites, a heated rooftop pool, a spa and health club, and the all-day Downtown restaurant. Guests rate it very highly — around 9.2/10 on the booking sites — for the location, the cleanliness, and staff who know how to look after sightseers.",
      "The one honest caveat is the setting itself: Tahrir is loud and traffic-choked, so ask for a higher, quieter room. But for being able to walk to the Egyptian Museum and back before dinner, it's one of the best-placed hotels in the city.",
    ],
    amenities: ["On Tahrir Square", "Faces the Egyptian Museum", "Heated rooftop pool", "Spa & health club", "Downtown restaurant & lounge bar", "295 rooms & suites", "Walk to Khan el-Khalili", "Business facilities"],
  }),
  build({
    slug: "hilton-grand-nile-cairo",
    name: "Hilton Cairo Grand Nile",
    city: "Cairo",
    region: "Cairo",
    destination: "cairo",
    area: "Corniche El Nil, Garden City",
    stars: 5,
    rating: "4.0",
    reviewCount: 12377,
    pricePerNight: 0,
    photos: 6,
    category: "Luxury",
    description: [
      "This is the great 41-storey tower on the tip of Roda Island, on the Corniche El Nil in Garden City — long known as the Grand Nile Tower (and originally the Grand Hyatt), and one of Cairo's most recognisable riverfront landmarks. Most of its ~715 rooms look straight down the Nile, and there's a revolving restaurant at the very top.",
      "Facilities match the scale: an outdoor pool, a spa with sauna and steam, a fitness centre, and a long list of restaurants and bars. It's central for the Egyptian Museum, Khan el-Khalili and downtown, and the Nile views — especially at sunset — are the headline.",
      "It's a large, older property, and some reviewers find the furnishings tired for a five-star, so it trades a little polish for those commanding views and a landmark location. We use it for travellers who want a proper Nile-front room in the middle of the city.",
    ],
    amenities: ["41-storey Nile-front tower", "Panoramic Nile views", "Revolving rooftop restaurant", "Outdoor pool", "Spa, sauna & steam", "Fitness centre", "Many restaurants & bars", "Central Garden City location"],
  }),
  build({
    slug: "hilton-cairo-nile-maadi",
    name: "Hilton Cairo Nile Maadi",
    city: "Cairo",
    region: "Cairo",
    destination: "cairo",
    area: "Maadi Corniche, on the Nile",
    stars: 5,
    rating: "4.5",
    reviewCount: 369,
    pricePerNight: 0,
    photos: 5,
    category: "Luxury",
    description: [
      "One of Cairo's newest luxury hotels, the Hilton Nile Maadi sits right on the Corniche in leafy, low-rise Maadi, directly on the river. From the higher rooms you get the Nile in the foreground and, on a clear day, the Pyramids far off on the horizon.",
      "It's a genuinely modern five-star — around 255 rooms and suites, a Nile-view fitness centre, the region's first eforea Spa, and dining that runs from grab-and-go to proper fine dining. Maadi's quiet, tree-lined streets make it a calmer base than downtown.",
      "The trade-off is distance: Maadi is well south of the main downtown and Giza sights, so expect longer drives to the museum and pyramids, and rates sit at the higher end. For a fresh, riverside stay away from the crush, it's excellent.",
    ],
    amenities: ["On the Nile in Maadi", "Nile & distant Pyramid views", "eforea Spa", "Nile-view fitness centre", "Multiple dining venues", "255 rooms & suites", "Quiet residential setting", "Newly built"],
  }),
  build({
    slug: "intercontinental-semiramis-cairo",
    name: "InterContinental Cairo Semiramis",
    city: "Cairo",
    region: "Cairo",
    destination: "cairo",
    area: "Corniche El Nil, Downtown",
    stars: 5,
    rating: "4.4",
    reviewCount: 5000,
    pricePerNight: 0,
    photos: 6,
    category: "Luxury",
    description: [
      "The InterContinental Semiramis is a Cairo institution — a riverfront giant on the Corniche El Nil, right beside the Egyptian Museum and Tahrir Square. Its rooftop pool has one of the best Nile panoramas in the city, and the location puts the whole of downtown within walking distance.",
      "It's best known for its food: nine outlets, from the all-day Night & Day to Birdcage (Thai), Pane Vino (Italian), The Grill and the Lebanese Sabaya by the Nile. Add a spa, a fitness centre, a casino, and Nile-view rooms, and it's a full-service base for a central Cairo stay.",
      "It's a very large, busy convention hotel, so public areas can feel crowded and some sections show their age. But for location, sunset views, and a genuinely good dining scene under one roof, it earns its long-standing reputation.",
    ],
    amenities: ["Nile-front on the Corniche", "Rooftop pool with Nile views", "Nine restaurants & bars", "Next to the Egyptian Museum", "Semiramis Spa & fitness", "Casino", "Nile & city-view rooms", "Walk to Tahrir & downtown"],
  }),
  // ============================ ALEXANDRIA ============================
  build({
    slug: "hilton-alexandria-corniche",
    name: "Hilton Alexandria Corniche",
    city: "Alexandria",
    region: "Alexandria",
    destination: "alexandria",
    area: "On the Mediterranean Corniche",
    stars: 5,
    rating: "4.1",
    reviewCount: 3295,
    pricePerNight: 0,
    photos: 6,
    category: "Luxury",
    description: [
      "The Hilton Alexandria Corniche sits right on the seafront, looking out over the Mediterranean along the city's famous curving Corniche. It's a modern, glassy five-star in a city short on them, and the sea views from the upper floors are the reason to be here.",
      "There's a rooftop pool, a spa and wellness centre, and around six restaurants and bars, plus a free shuttle to a private beach. It ranks among the top hotels in Alexandria and scores well for cleanliness, the central seafront position, and those Mediterranean views.",
      "Service can be a little inconsistent for a five-star, and a few guests find breakfast underwhelming, so it's not flawless — but for a contemporary, sea-facing base in the heart of Alexandria, it's the obvious choice.",
    ],
    amenities: ["On the Mediterranean Corniche", "Sea-view rooms & suites", "Rooftop pool", "Spa & wellness centre", "~6 restaurants & bars", "Shuttle to a private beach", "Central seafront location"],
  }),
  build({
    slug: "steigenberger-cecil-alexandria",
    name: "Steigenberger Cecil Hotel Alexandria",
    city: "Alexandria",
    region: "Alexandria",
    destination: "alexandria",
    area: "Saad Zaghloul Square, seafront",
    stars: 4,
    rating: "4.0",
    reviewCount: 1200,
    pricePerNight: 0,
    photos: 5,
    category: "Boutique",
    description: [
      "The Cecil is Alexandria's most storied hotel — a 1929 landmark on Saad Zaghloul Square at Raml Station, looking out over the Corniche and the sea. In its time it housed British Intelligence during the war and hosted everyone from Churchill and Agatha Christie to Om Kalthoum; you can still feel that faded-grandeur atmosphere in the lobby.",
      "Run under the Steigenberger name since 2014, it blends the old colonial bones — cage lift, high ceilings, sea-facing balconies — with modern comforts. It's a four-star, so it's about character and location rather than resort facilities, and it puts you right in the historic heart of the city.",
      "As a heritage building it shows its age: expect some street noise, dated corners, and limited parking. But if you want to sleep inside a piece of Alexandria's history, on the seafront, nothing else comes close.",
    ],
    amenities: ["Historic 1929 landmark", "On Saad Zaghloul Square, seafront", "Sea-view rooms", "Colonial-era architecture", "Restaurant & bar", "Central Raml Station location", "Steigenberger-managed"],
  }),
  // ============================ LUXOR ============================
  build({
    slug: "steigenberger-nile-palace-luxor",
    name: "Steigenberger Nile Palace Luxor",
    city: "Luxor",
    region: "Luxor",
    destination: "luxor",
    area: "East Bank, on the Nile",
    stars: 5,
    rating: "4.4",
    reviewCount: 3200,
    pricePerNight: 0,
    photos: 6,
    category: "Resort",
    description: [
      "The Steigenberger Nile Palace runs right along the Nile on Luxor's East Bank, with its own boat dock and a wall of rooms facing the water and the Theban hills beyond. Karnak and Luxor Temples are a short drive, and the Valley of the Kings sits just across the river — you can watch the sun set behind it from your balcony.",
      "It's a proper resort: around 303 rooms and suites, two outdoor pools plus a children's pool, the Suraya Spa and health club, landscaped gardens, and several restaurants and bars including the Nile Lounge. The riverfront setting, especially at sunset, is the standout.",
      "Some rooms and public areas feel a little dated and due for a refresh, so it's not the newest option in town — but for a Nile-front base with pools, gardens, and sunset views over the West Bank, it's a reliable, comfortable choice.",
    ],
    amenities: ["Nile-front with private dock", "Two outdoor pools + kids' pool", "Suraya Spa & health club", "Nile-view rooms & balconies", "Landscaped gardens", "Several restaurants & bars", "Near Karnak & Luxor Temples", "Sunset West Bank views"],
  }),
  build({
    slug: "sonesta-st-george-luxor",
    name: "Sonesta St. George Hotel Luxor",
    city: "Luxor",
    region: "Luxor",
    destination: "luxor",
    area: "East Bank, central Luxor",
    stars: 5,
    rating: "4.3",
    reviewCount: 2100,
    pricePerNight: 0,
    photos: 6,
    category: "Luxury",
    description: [
      "The Sonesta St. George sits on the East Bank in central Luxor, on the Nile and within easy reach of Luxor Temple, the museum, and Karnak just to the north. Its Royal Rooms and Ambassador Suites look straight out over the river, and there's a riverside pool with deck seating for the hot afternoons.",
      "Dining is a real strength here: the Miyako Japanese restaurant and Beban Italian sit among three restaurants and three bars, and there's a spa, a health club with classes, and even a library. It's a polished five-star that manages to feel warm rather than corporate.",
      "The odd unrenovated room shows some dated decor, and central Luxor means a little street noise, so ask for a Nile-facing room high up. Otherwise it's one of the most dependable, well-located stays on the East Bank.",
    ],
    amenities: ["Nile-front, central Luxor", "Front-Nile rooms & suites", "Riverside pool & deck", "Miyako (Japanese) & Beban (Italian)", "Three restaurants, three bars", "Spa & health club", "Near Luxor Temple & Karnak", "Library"],
  }),
  // ============================ ASWAN ============================
  build({
    slug: "tolip-aswan",
    name: "Tolip Aswan Hotel",
    city: "Aswan",
    region: "Aswan",
    destination: "aswan",
    area: "On the Nile Corniche, downtown",
    stars: 5,
    rating: "4.3",
    reviewCount: 520,
    pricePerNight: 0,
    photos: 6,
    category: "Resort",
    description: [
      "The Tolip Aswan sits on the Nile in downtown Aswan, on the Corniche side rather than an island, so you get full and partial river views from private balconies while staying walkable to the town and souq. It's a large, self-contained five-star with a distinctly local, family-holiday feel.",
      "The 195 rooms and chalets come with the usual comforts, and the facilities go further than most: outdoor and indoor pools, gardens, a gym and spa, and unusual extras like a bowling alley and a cinema. Several restaurants and bars serve buffet and à la carte with the river in view.",
      "Decor and furnishings feel dated in places and the property is arguably due a refresh, so it's more comfortable-and-fun than sleek. But for a Nile-view room, plenty to do on site, and an easy walk into Aswan, it's good value.",
    ],
    amenities: ["Nile-front on the Corniche", "Nile-view balconies", "Indoor & outdoor pools", "Gym & spa", "Bowling alley & cinema", "Several restaurants & bars", "Gardens", "Walk to Aswan souq"],
  }),
  build({
    slug: "pyramisa-isis-island-aswan",
    name: "Pyramisa Isis Island Aswan Resort",
    city: "Aswan",
    region: "Aswan",
    destination: "aswan",
    area: "Private island in the Nile",
    stars: 5,
    rating: "4.0",
    reviewCount: 640,
    pricePerNight: 0,
    photos: 6,
    category: "Resort",
    description: [
      "The Pyramisa Isis Island resort has one of Aswan's most romantic settings — its own island in the middle of the Nile, ringed by some 28 acres of tropical gardens with the river, the desert mountains, and the city spread out around it. A free hotel ferry runs to the mainland around the clock, every 15 minutes.",
      "All 450 rooms and suites look over the river, gardens, or pools, and there are indoor and outdoor pools, a spa with sauna, and four restaurants. The island quiet — birdsong, water, and green — is the whole appeal after a day of temples and heat.",
      "Service and maintenance can be inconsistent, and the ferry-only access won't suit everyone, so manage expectations on polish. But if the idea of your own green island in the Nile appeals, few places in Egypt deliver it like this.",
    ],
    amenities: ["Private island in the Nile", "28 acres of tropical gardens", "Free 24-hour ferry", "Indoor & outdoor pools", "Spa with sauna", "Four restaurants", "River, garden & pool views", "Near the Aga Khan Mausoleum"],
  }),
  build({
    slug: "citymax-aswan",
    name: "Citymax Hotel Aswan",
    city: "Aswan",
    region: "Aswan",
    destination: "aswan",
    area: "Nile Corniche, central Aswan",
    stars: 4,
    rating: "4.1",
    reviewCount: 210,
    pricePerNight: 0,
    photos: 6,
    category: "Comfort",
    description: [
      "The Citymax is a modern four-star right on Aswan's Corniche, steps from the Nile and within a short walk of the souq and the main sights. It's newer and more contemporary than most of Aswan's big river hotels, which makes it a clean, straightforward base in a great spot.",
      "The standout is the rooftop pool, which catches the Nile and Aswan's famous sunsets. There are around 79 air-conditioned rooms (some with river views), a café, a sauna, jacuzzi and small spa, and an all-day restaurant serving Middle Eastern food and a buffet breakfast.",
      "It's a smaller property, so don't expect the sprawling grounds or facilities of the island resorts. But for a modern, well-located, fairly priced room a short walk from everything in Aswan, it punches above its size.",
    ],
    amenities: ["On the Nile Corniche", "Rooftop pool with sunset views", "River-view rooms", "Café, sauna & jacuzzi", "Small spa", "All-day restaurant", "Walk to the souq", "Free parking"],
  }),
  // ============================ ABU SIMBEL ============================
  build({
    slug: "azal-lagoons-abu-simbel",
    name: "Azal Lagoons Resort Abu Simbel",
    city: "Abu Simbel",
    region: "Abu Simbel",
    destination: "abu-simbel",
    area: "On Lake Nasser",
    stars: 5,
    rating: "4.4",
    reviewCount: 247,
    pricePerNight: 0,
    photos: 6,
    category: "Resort",
    description: [
      "Azal Lagoons is the newest and smartest place to stay in Abu Simbel — a large five-star resort that opened in 2023 right on the shore of Lake Nasser, about a ten-minute drive from the temples and barely a kilometre from the little airport. After the long journey south, arriving somewhere this fresh and well-kept is a genuine relief.",
      "The grounds are expansive, with an outdoor pool and pool bar, a fitness centre, a spa, gardens, and three restaurants covering Mediterranean and Middle Eastern cooking. Rooms and suites are modern and well-equipped, and guests regularly mention generous free upgrades.",
      "It's very new and a little isolated on the lake, so it's a short drive from the temples and town rather than walking distance, and a handful of reviews are still mixed as it finds its feet. But for comfort and facilities in a place that has historically had few good hotels, it's a standout.",
    ],
    amenities: ["On Lake Nasser", "Opened 2023 — modern", "Outdoor pool & pool bar", "Spa & fitness centre", "Three restaurants", "Gardens", "~10 min to the temples", "1 km from Abu Simbel airport"],
  }),
  build({
    slug: "retac-nefertari-abu-simbel",
    name: "Retac Abu Simbel Nefertari Hotel",
    city: "Abu Simbel",
    region: "Abu Simbel",
    destination: "abu-simbel",
    area: "Abu Simbel town, by the temples",
    stars: 4,
    rating: "4.1",
    reviewCount: 127,
    pricePerNight: 0,
    photos: 6,
    category: "Value",
    description: [
      "The Nefertari sits right in the heart of Abu Simbel town, less than a kilometre from the Sun Temple of Ramses II and the Temple of Nefertari, with views over Lake Nasser. Its trump card is that location: you can be at the temples for the quiet early-morning light in minutes, before the convoys arrive.",
      "It's a straightforward four-star with 120 rooms, a restaurant, a lounge and bar, and two outdoor pools, plus a 24-hour desk and parking. Nothing flashy — just a solid, convenient base in a town that has very few of them.",
      "It's an older, simpler property, so rooms and amenities are more basic than the newer lakeside resorts nearby. But if being a two-minute drive from the temples matters more to you than luxury, it's the practical choice.",
    ],
    amenities: ["In the heart of Abu Simbel town", "0.7 km to the temples", "Lake Nasser views", "Two outdoor pools", "Restaurant, lounge & bar", "120 rooms", "24-hour front desk", "Free parking & Wi-Fi"],
  }),
  // ============================ HURGHADA ============================
  build({
    slug: "tropitel-sahl-hasheesh",
    name: "Tropitel Sahl Hasheesh",
    city: "Hurghada",
    region: "Hurghada",
    area: "Sahl Hasheesh bay",
    stars: 5,
    rating: "4.2",
    reviewCount: 3200,
    pricePerNight: 0,
    photos: 5,
    category: "Resort",
    description: [
      "Tropitel Sahl Hasheesh is a big, all-inclusive beach resort in the calm bay of Sahl Hasheesh, about 25 minutes south of Hurghada airport. It's built for a proper Red Sea holiday — a long private sandy beach, several freshwater pools, and a jetty that runs out over a genuinely good house reef.",
      "There are around 543 rooms and suites, five restaurants plus bars, a spa and fitness centre, and a kids' club, so families and divers both do well here. The snorkelling straight off the jetty is a real highlight — you're in clear water over coral within minutes of breakfast.",
      "Being out in Sahl Hasheesh, it's a little isolated: reaching Hurghada's shops and nightlife means a taxi or shuttle. But if you want beach, reef, and all-inclusive ease without leaving the resort, that isolation is rather the point.",
    ],
    amenities: ["Private sandy beach", "House reef off the jetty", "Several freshwater pools", "All-inclusive", "Five restaurants + bars", "Spa & fitness centre", "Kids' club", "25 min from the airport"],
  }),
  build({
    slug: "continental-hurghada",
    name: "Continental Hotel Hurghada",
    city: "Hurghada",
    region: "Hurghada",
    area: "Seafront, south of Hurghada",
    stars: 5,
    rating: "4.2",
    reviewCount: 8500,
    pricePerNight: 0,
    photos: 6,
    category: "Resort",
    description: [
      "The Continental Hurghada is a big, deluxe seafront resort just south of Hurghada town — for years it was the Mövenpick, and it kept the sprawling, garden-filled scale that made that name work. It sits on a sandy Red Sea beach with its own marina, across some 135,000 square metres of tropical planting.",
      "There's a large spread of rooms and suites, multiple restaurants and bars, daily entertainment, a health club, a heated winter pool, water sports, and a private diving centre. Being close to town (about 7 km from the centre) makes it easy to nip out, unlike the more isolated bays.",
      "As a former Mövenpick, some rooms and corners feel dated and in need of a refresh, so it's more comfortable-classic than cutting-edge. But for a full-service beach resort with gardens, a marina, and town on the doorstep, it delivers.",
    ],
    amenities: ["Sandy Red Sea beach & marina", "135,000 m² of gardens", "Multiple restaurants & bars", "Heated winter pool", "Private diving centre", "Water sports", "Health club", "~7 km to Hurghada centre"],
  }),
  build({
    slug: "steigenberger-aldau-beach-hurghada",
    name: "Steigenberger ALDAU Beach Hotel",
    city: "Hurghada",
    region: "Hurghada",
    area: "Private beach, southern Hurghada",
    stars: 5,
    rating: "4.5",
    reviewCount: 6000,
    pricePerNight: 0,
    photos: 6,
    category: "Resort",
    description: [
      "The Steigenberger ALDAU Beach is a slick, all-suite resort at the southern edge of Hurghada, built in a low, Swahili-inspired style along its own half-kilometre of private beach — about fifteen minutes from the airport. After a recent renovation it's one of the more polished big resorts on this coast.",
      "The headline is the 5,000-square-metre pool landscape with its signature lazy river, backed up by the indoor Pure Spa (heated pool, hammam, sauna), the Ilios dive and aqua centre on the beach, and four restaurants and five bars. Suites are spacious, most with furnished balconies and sea views, and there's 24-hour room service.",
      "It's large and geared towards conferences as well as holidays, so it can feel busy and less intimate than a boutique bolthole. But for space, a serious pool complex, a good house reef, and reliable Steigenberger polish, it's one of Hurghada's strongest.",
    ],
    amenities: ["Private half-km beach", "5,000 m² pool & lazy river", "All-suite, sea-view balconies", "Pure Spa (hammam, sauna)", "Ilios dive & aqua centre", "Four restaurants, five bars", "24-hour room service", "15 min from the airport"],
  }),
  // ============================ SHARM EL SHEIKH ============================
  build({
    slug: "movenpick-sharm-el-sheikh",
    name: "Mövenpick Resort Sharm El Sheikh",
    city: "Sharm El Sheikh",
    region: "Sharm El Sheikh",
    destination: "sharm-el-sheikh",
    area: "Above Naama Bay",
    stars: 5,
    rating: "4.3",
    reviewCount: 3900,
    pricePerNight: 0,
    photos: 6,
    category: "Resort",
    description: [
      "The Mövenpick Resort sits high above Naama Bay, Sharm's liveliest strip, in lush terraced gardens that tumble down to five private beaches with clear water and house-reef snorkelling. That elevated, green setting — rare in Sharm — gives it sweeping Red Sea views and a calmer feel than the beachfront giants.",
      "There are 298 Arabian-style rooms and villas, most with sea views, and around ten restaurants and bars including the Indian Rangoli and the Arabian grill El Kebabgi. Add multiple pools, the Lotus Spa, four tennis courts, and an on-site dive centre, and it's a complete resort ten minutes from the airport and town.",
      "The one thing to know is the hilltop layout: lots of steps and steep paths down to the beaches, which is tiring if stairs are a problem, and parts of the resort feel dated. But for gardens, views, and reef right off your own beach, it's a Sharm classic.",
    ],
    amenities: ["Above Naama Bay", "Five private beaches & house reef", "Lush terraced gardens", "Multiple pools", "~10 restaurants & bars", "Lotus Spa", "Dive centre & tennis courts", "10 min from the airport"],
  }),
  build({
    slug: "hilton-sharm-fayrouz",
    name: "Hilton Sharm El Sheikh Fayrouz Resort",
    city: "Sharm El Sheikh",
    region: "Sharm El Sheikh",
    destination: "sharm-el-sheikh",
    area: "Naama Bay",
    stars: 4,
    rating: "4.4",
    reviewCount: 1934,
    pricePerNight: 0,
    photos: 6,
    category: "Resort",
    description: [
      "The Fayrouz — for years the Hilton Sharm El Sheikh Fayrouz Resort — is a low-rise village of bungalow rooms scattered through gardens on its own sandy beach in Naama Bay. Everything is at ground level and spread out, which gives it a relaxed, unhurried feel, and it's a flat five-minute beachfront stroll into the heart of Naama Bay's restaurants and shops.",
      "There are several pools, a private beach with a snorkellable house reef, a spa, and a handful of restaurants and bars including an Italian. Guests consistently praise the location, the low-density layout, and the friendly staff — it's an easy, comfortable base right where the action is, ten minutes from the airport.",
      "Two honest notes: the resort has recently rebranded (it now trades as Jaz Fayrouz, so Hilton loyalty benefits no longer apply), and some rooms and facilities show their age. But as a well-placed, low-rise beach village in Naama Bay, it still does the job nicely.",
    ],
    amenities: ["Private beach in Naama Bay", "House reef snorkelling", "Low-rise bungalow rooms", "Several pools", "Spa", "Walk to Naama Bay centre", "Restaurants & bars", "10 min from the airport"],
  }),
  // ============================ SIWA ============================
  build({
    slug: "kenooz-shali-lodge-siwa",
    name: "Kenooz Shali Lodge",
    city: "Siwa",
    region: "Siwa",
    destination: "siwa",
    area: "Siwa town, by the Shali fortress",
    stars: 3,
    rating: "4.4",
    reviewCount: 179,
    pricePerNight: 0,
    photos: 5,
    category: "Eco-lodge",
    description: [
      "Shali Lodge is a small kershef eco-lodge in the middle of Siwa town, built by EQI — the same team behind the legendary Adrere Amellal — from salt-rock and mud brick in the traditional Siwan way. It's tucked into a shaded date-palm garden beside the ruined Shali fortress, with a spring-fed pool and the souk just steps away.",
      "The sixteen or so rooms are hand-built in local style: plastered kershef walls, palm-frond furniture, Bedouin carpets, and the thick earthen walls keeping things naturally cool. Breakfast is served on a palm-shaded terrace, and the whole place has the quiet, low-impact feel that makes Siwa special.",
      "It's rustic by design — rooms are simple and lean on natural cooling rather than modern air-conditioning, which not everyone expects at the price. But for staying inside Siwa's own architecture, in the heart of the oasis, it's characterful in a way no concrete hotel can match.",
    ],
    amenities: ["Traditional kershef architecture", "Spring-fed garden pool", "Date-palm gardens", "Beside the Shali fortress", "Steps from Siwa souk", "Breakfast on a shaded terrace", "EQI eco-lodge", "Naturally cooled rooms"],
  }),
  build({
    slug: "dream-lodge-siwa",
    name: "Dream Lodge Siwa",
    city: "Siwa",
    region: "Siwa",
    destination: "siwa",
    area: "Siwa Oasis, palm gardens",
    stars: 3,
    rating: "4.3",
    reviewCount: 54,
    pricePerNight: 0,
    photos: 5,
    category: "Eco-lodge",
    description: [
      "Dream Lodge is a small eco-lodge built in the traditional Siwan style, set in a lush palm garden with an outdoor pool and terrace on the edge of the oasis. It's an easy base for Siwa's sights — about a kilometre from the Temple of the Oracle and Cleopatra's Spring, with the Mountain of the Dead nearby.",
      "Rooms have handcrafted local furniture, Siwi rugs, and private balconies over the garden, plus air-conditioning, kitchenettes and mini-bars — a touch more modern comfort than the purist mudbrick lodges. Breakfast is served poolside, dinner by the fireplace, and the desk will sort desert trips and bikes.",
      "It's a modest, independently run place, so service and upkeep can be a little hit-and-miss compared with Siwa's higher-end retreats. But for a relaxed, green, affordable stay close to the temples, it's a lovely low-key choice.",
    ],
    amenities: ["Traditional Siwan-style build", "Palm garden & outdoor pool", "Balconies over the garden", "Air-conditioning & kitchenettes", "Near the Temple of the Oracle", "Poolside breakfast, fireside dinner", "Desert excursions arranged", "Bike & car rental"],
  }),
];

export const getHotel = (slug: string) => hotels.find((h) => h.slug === slug);
